### ISSUE TITLE
Sensor Usage Implementation

### ISSUE THREAD

**Issue by dawsynth** [RocketryVT/active-drag-system#1]
This is the ongoing issue for the implementation of the communication between the BeagleBone and any sensors (primarily the IMU and Altimeter). This will likely be accomplished via one of the Programmable Real-time Units (PRU) featured on the BeagleBone Black. The PRUs are essentially co-processors that lives on the same board for easing repetitive processes (such as input/output) off of the main CPU. A couple of references for the PRUs' usage can be found in the last chapters of the book "Exploring BeagleBone" by Derek Molloy as well as at [this website](https://www.glennklockwood.com/embedded/beaglebone-pru.html). A current, working design (in pseudo-code) for the class structure is as follows:

```
class Sensor {
    private Logger log;
    private altimeterSetup();
    private imuSetup();
    update();
}
```

Please document any updates or changes made for this implementation within this issue's thread.

**Comment by gregoryw3** [comment]
- Using Boost::ASIO for asynchronous non blocking I/O access. Allows simultaneous reading and writing.
    - https://gist.github.com/kaliatech/427d57cb1a8e9a8815894413be337cf9
    - Using this as guide for implementing Boost::ASIO
- Found reference Adafruit cpp files we can use for BNO055 (imu) and MPL3115A2 (alt) as a basis
   - They both rely on arduino libraries so we can't use them directly but they tell us the control flow and memory addresses to use.
- Don't understand how servos work (in c++)?
   - Is it just sending an int to a /dev/ gpio and thats it? 
   - https://stackoverflow.com/questions/71042253/what-are-my-options-for-pwm-using-c-on-the-google-coral-dev-board
      - ```shell 
        echo 0 > /sys/class/pwm/pwmchip0/export
        echo 50000 > /sys/calss/pwm/pwmchip0/pwm0/period
        echo 25000 > /sys/calss/pwm/pwmchip0/pwm0/duty_cycle
        ehco 1 > /sys/calss/pwm/pwmchip0/pwm0/enable 
        ```

**Comment by dawsynth** [comment]
So to answer your question on how servos work, I believe it is a matter of just writing the desired values to the correct memory addresses. There is an example in the book on how to control a PWM signal via the PRU in C. It should be on page 704, but here is the provided source straight from the book:

```C
#include <stdint.h>
#include <pru_cfg.h>
#include "resource_table_empty.h"
// Delay factor which defines the PWM frequency
#define DELAYFACTOR 10
volatile register uint32_t __R30;
volatile register uint32_t __R31;

void main(void) {
  volatile uint32_t gpio, button;
  uint32_t percent, count;
  // The PWM percentage (0-100) for the positive cycle
  percent = 75;
  // Use pru0_pru_r30_5 as an output i.e., 100000 or 0x0020
  gpio = 0x0020;
  // Use pru0_pru_r31_3 as a button i.e., 1000 or 0x0008
  button = 0x0008;
  // Stop the loop when the button is pressed
  while (!(__R31 && button)) {
    for(count=0; count<100; count++) {
      // Use two comparisons to equalize the timing
      if(count<=percent) { __R30 |= gpio; }
      if(count> percent) { __R30 &= (~gpio); }
      __delay_cycles(DELAYFACTOR);
    }
  }
  __halt();
}
```

One thing I find interesting in this implementation is its direct use of registers within C. Not something you see everyday, even in embedded devices.

**Comment by gregoryw3** [comment]
Thanks! Although both adafruit sensors also use direct registers. So idk if thats for the onboard module firmware or for users...
